
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mGageTest_development

test:
  <<: *default
  database: mGageTest_test

production:
  <<: *default
  database: mGageTest_production
  username: mGageTest
  password: <%= ENV['MGAGETEST_DATABASE_PASSWORD'] %>
